### ISSUE TITLE
Create stub files for all exercises

### ISSUE THREAD

**Issue by kytrinyx** [exercism/crystal#175]
We have decided to require all file-based tracks to provide stubs for their exercises.

The lack of stub file generates an unnecessary pain point within Exercism, contributing a significant proportion of support requests, making things more complex for our students, and hindering our ability to automatically run test-suites and provide automated analysis of solutions.

We believe that it’s essential to understand error messages, know how to use an IDE, and create files. However, getting this right as you’re just getting used to a language can be a frustrating distraction, as it can often require a lot of knowledge that tends to seep in over time. At the start, it can be challenging to google for all of these details: what file extension to use, what needs to be included, etc. Getting people up to speed with these things are not Exercism’s focus, and we’ve decided that we are better served by removing this source of confusion, letting people get on with actually solving the exercises.

The original discussion for this is at https://github.com/exercism/discussions/issues/238.

Therefore, we’d like this track to provide a stub file for each exercise.

- If this track already provides stub files for all exercises, please close this issue.
- If this track already has an open issue for creating stubs, then my apologies. Please close one as a duplicate.
- Otherwise, please respond to this issue with useful details about what needs to be done to complete this task in this track so that people who are not familiar with the track may easily contribute.

**Comment by mhelmetag** [comment]
I believe we've had stubs since the beginning For crystal, they're blank files in the `src` directory of the exercise that work with the `crystal spec` command and have a comment to add your solution there.

I think we're all good then.

**Comment by nathanchere** [comment]
I don't think it's all good. Talking about pain points for getting started, most other language tracks do this a lot better. For example:

```
module Gigasecond
  def from(start : Time) : Time
    # Please implement your solution to gigasecond in this file
  end
end
```

is a lot better than

```
# Please implement your solution to gigasecond in this file
```

I think it would make a significant difference to making the Crystal track more welcoming and encouraging for newcomers.

**Comment by mhelmetag** [comment]
So I have seen tracks do it both ways (having a stub with a method, module, class, etc) or an empty file and there are pros and cons of both.

I think that having a default stub with a module (or anything for that matter) is too prescriptive. I think the blank file allows the solver to try anything that fits. I also think it's a nice intro to TDD and "simple green". Crystal can't find the namespace `Gigasecond` so make a class or module or whatever. Crystal can't find a method in that namespace so make that method. Etc.

I think we could add stubs in the first few "core" exercises but... we first need to pick which exercises those are.

If you have some suggestions for "core" exercises (or any additions to round out that core set), it'd be awesome to have a PR with better stubs for those exercises and the updated track config file.
