### ISSUE TITLE
Problem with Resistor-Color-Duo 

### ISSUE THREAD

**Issue by konung** [exercism/crystal#184]
This particular exercise (at least in Crystal track) has a logic error. 
https://exercism.io/my/solutions/bd58d29f62564188a2cb39e716d7d797

The test suite expects output as an int, however, it will fail for this particular test:

```crystal
  it "Black and Yellow" do
    ResistorColorDuo.value(["black", "yellow"]).should eq(04)
  end
```

If the first color in the input is `black => 0` according to the instructions, which will result in `4` as output since the string "04", when cast into an integer, will return `4`. Thus causing electrocution or spaceship explosion, or some other unintended result. 

Either the instructions need to change and say "black" will never be the first color or the test suite should check for `string` rather than `int`

**Comment by iHiD** [comment]
Moved to the Crystal track.

**Comment by mhelmetag** [comment]
Howdy!

I'd definitely appreciate a PR to the generator for this exercise! If not, I can do it as well. Thanks for brining this issue up.

**Comment by marksiemers** [comment]
@konung - I believe this is resolved, can you confirm?

**Comment by konung** [comment]
Yes I believe so.
