### ISSUE TITLE
Track introduction is missing

### ISSUE THREAD

**Issue by kruschk** [exercism/crystal#188]
The [Crystal track page](https://exercism.io/my/tracks/crystal) is missing an introduction; the default "TODO: The maintainers have not provided an introduction for this track" message is displayed instead.

I think the only change required is for a non-empty string to be added in the "blurb" property of the [track configuration JSON file](https://github.com/exercism/crystal/blob/master/config.json). I'd be willing to fix this if a maintainer would help me come up with an appropriate description!

**Comment by marksiemers** [comment]
@kruschk - I think this has been resolved: https://github.com/exercism/crystal/blob/main/config.json#L11

Can you take a look and confirm?

**Comment by kruschk** [comment]
I tried to confirm, but I can't seem to locate the blurb text on the Crystal track, or any other track, for that matter. It looks like the site now uses [docs/ABOUT.md](https://github.com/exercism/crystal/blob/main/docs/ABOUT.md) instead of the blurb, but I'm not sure.

**Comment by ErikSchierboom** [comment]
Yep, this can be closed!
