### ISSUE TITLE
[Templates]: Use standard-libary methods

### ISSUE THREAD

**Issue by meatball133** [exercism/crystal#405]
We have implemented some custom methods that are already in the core language, to make the templates easier to maintain, there is a need to start using the standard methods.

This involves going through all of the practice exercise templates and replacing `to_capitalized` with the built-in method `camelcase`.
And `to_snake` with the built in method `underscore`.

**Comment by meatball133** [comment]
Seems like I didn't think it through all the way but the to_capitalized method in GeneratorHelp can still be simplified. Since what has to happen is the `-` has to be replaced by `_`. And that would make that method quite light which would be nice. So if you like you could update that method and replace to use the underscore method elsewhere.

**Comment by ls1955** [comment]
Guess I would begin working on this issue, then. :D
