### ISSUE TITLE
Bad grammar in Wellington Weather Station instructions?

### ISSUE THREAD

**Issue by avrame** [exercism/crystal#453]
This sentence doesn't make sense to me: "To build a complete temperature measurement unit so are 4 temperature sensors required."
https://github.com/exercism/crystal/blob/e987438d615e1641c06ee49c0174b268716a13de/exercises/concept/wellingtons-weather-station/.docs/instructions.md?plain=1#L86
The part that is confusing/wrong is "unit so are"

**Comment by meatball133** [comment]
Yeah, you are right, that doesn't read quite well:

Do you think changing it to something like this fixes it?
> A Temperature measurement unit, requires 4 temperature sensors to build.

**Comment by ryanplusplus** [comment]
How about this?

> Each temperature measurement unit requires 4 temperature sensors.

**Comment by meatball133** [comment]
Sounds good!

Do you want to pr it or shall I?

**Comment by ryanplusplus** [comment]
> Sounds good!
> 
> Do you want to pr it or shall I?

I'll put one up now
