### ISSUE TITLE
Incorrect statement about loop conditions

### ISSUE THREAD

**Issue by avrame** [exercism/crystal#459]
https://github.com/exercism/crystal/blob/c081fc279ccf5e7d438f74da0dd9d8aa51fe3a1b/exercises/concept/interest-is-interesting/.docs/introduction.md?plain=1#L11

Shouldn't this be "The condition is evaluated before the code within the loop is executed, which means that if the condition is _false_ the code within the loop will never be executed."

(changed "true" to "false")

**Comment by meatball133** [comment]
Yes
