### ISSUE TITLE
Confusing sentence about method return values

### ISSUE THREAD

**Issue by avrame** [exercism/crystal#460]
https://github.com/exercism/crystal/blob/c081fc279ccf5e7d438f74da0dd9d8aa51fe3a1b/exercises/concept/interest-is-interesting/.docs/introduction.md?plain=1#L129

This sentence has incorrect grammar. Should it simply read "In Crystal, the last expression in a method returns its value."?

**Comment by meatball133** [comment]
Yes, that sounds good.
