### ISSUE TITLE
Inconsistent class method names

### ISSUE THREAD

**Issue by ls1955** [exercism/crystal#502]
In Chess Game exercise,  it is `Chess.nickname` inside the [instructions](https://github.com/exercism/crystal/blob/main/exercises/concept/chess-game/.docs/instructions.md), while it is `Chess.nick_name` inside the [spec](https://github.com/exercism/crystal/blob/main/exercises/concept/chess-game/spec/chess_game_spec.cr) and [src](https://github.com/exercism/crystal/blob/main/exercises/concept/chess-game/src/chess_game.cr) file.

Should we unify the method_names?

**Comment by meatball133** [comment]
Yes, I think we should use `Chess.nickname`, should I assign you to this issue?

**Comment by ls1955** [comment]
Sure, I would work on it right away. :D
