### ISSUE TITLE
Some possible language/typo corrections to the Library of Luton exercise README

### ISSUE THREAD

**Issue by rjpgt** [exercism/crystal#570]
Under **Introduction**:

1st para, second line:
 "Their size makes so they are memory efficient, and also gives it certain properties that Strings don't have."
Possible correction:
"Their size makes them memory efficient, and also gives them certain properties that Strings don't have."

2nd para, first line:
"When working with Strings in Crystal is it quite common to work with Chars..."
Possible correction:
"When working with Strings in Crystal it is quite common to work with Chars..."

2nd para, second line:
"For example, the String#[] method returns a Char, or the String#chars method..."
Possible correction:
"For example, the String#[] method returns a Char, and the String#chars method..."

Under **Incrementing / Decrementing**:

First para, first line:
"Due to char being a 32 Unicode point do they support incrementing and decrementing, this makes it so if you have 'a' so can you get 'b' by adding one."
Possible correction:
"Due to Char being a 32 Unicode point it supports incrementing and decrementing. For example, if you have 'a' you can get 'b' by adding one."

Under **concatenation**:

First para:
"Since Chars is only meant to represent a 32-bit Unicode, can't 2 chars be concatenation. Thereby Chars can only be concatenated with Strings."
Possible correction:
"Since a Char is only meant to represent a single 32-bit Unicode point, concatenation of 2 Chars is not allowed. Chars can only be concatenated with Strings."

"Properties methods"
Possible correction: "Properties, methods"

Under **Converting between code points and Chars**:
First para, first line:
"Since Chars is a 32-bit Unicode point, so can you convert between Chars and code points (Int)."
Possible correction:
"Since a Char is a 32-bit Unicode point, you can convert between Chars and code points (Int)."

**Comment by ryanplusplus** [comment]
These all look good to me. Can you create a pull request with these fixes?
