### ISSUE TITLE
[spellbound-steel] Incorrect instruction and example for last question?

### ISSUE THREAD

**Issue by ls1955** [exercism/crystal#690]
The last question (4. Decode a card) of [exercise](https://exercism.org/tracks/crystal/exercises/spellbound-steel) instructs us to take every second character and reverse it, although reverse is not required from the actual specs. The provided example `SpellboundSteel.decode_card("Wraoir")` should returns `"Wai"` instead of `"Warrior"`.

**Comment by ryanplusplus** [comment]
Thanks @ls1955 -- you're right, this is incorrect.

@meatball133 I'm not sure where this exercise came from. Is the correct behavior what's described in the instructions or what's given in the tests?

**Comment by meatball133** [comment]
The instruction is incorrect
