### ISSUE TITLE
[Markdown]  Failing specs before doing anything 

### ISSUE THREAD

**Issue by ls1955** [exercism/crystal#694]
The [exercise](https://exercism.org/tracks/crystal/exercises/markdown) mentioned all tests should be passing initially. When I run the specs, four specs are failing:
```bash
crystal spec spec/markdown_spec.cr:93 # Markdown unordered lists
crystal spec spec/markdown_spec.cr:102 # Markdown With a little bit of everything
crystal spec spec/markdown_spec.cr:120 # Markdown with markdown symbols in the list item text that should not be interpreted
crystal spec spec/markdown_spec.cr:137 # Markdown unordered lists close properly with preceding and following lines
```

After modifying 2 places, all specs had passed:
1. At [last line of `Markdown#to_html`](https://github.com/exercism/crystal/blob/main/exercises/practice/markdown/src/markdown.cr#L23), change `lines.join("\n")` to `lines.join`. Because it seems like html output in specs does not contains `'\n'`.
2. At [second condition of `Markdown#parse_list`](https://github.com/exercism/crystal/blob/main/exercises/practice/markdown/src/markdown.cr#L30), change `!previous_line.starts_with?('*')` to `!previous_line.starts_with?(/<(ul|li)>/)`. Old condition failed because it checks previous line in markdown format. If there is previous line, it is already transformed into html format.

**Comment by ryanplusplus** [comment]
Hey @ls1955, good catch. Would you mind creating a PR with your suggested changes?

**Comment by meatball133** [comment]
Good catch, I will look into making the ci able to test against the normal solution for this exercise as well.
