### ISSUE TITLE
[BookStore] Inconsistent price per book?

### ISSUE THREAD

**Issue by ls1955** [exercism/crystal#696]
[Exercise's instructions](https://exercism.org/tracks/crystal/exercises/book-store) said book price is `$8`, though it seems like book price in specs are `$800`, is it intentional?

**Comment by ryanplusplus** [comment]
Confusingly, the prices are in centa, not dollars. The upstream problem specification indicates that floats should not be used and a language-appropriate fixed point format should be used instead. I'm not aware of any built-in support so using an integer representation of price as cents is the way we went.

**Comment by meatball133** [comment]
We are not going to change the instructions, what can be done is an append.

**Comment by meatball133** [comment]
Using an append file, e.g: https://github.com/exercism/crystal/blob/main/exercises/practice/roman-numerals/.docs/instructions.append.md

**Comment by meatball133** [comment]
Sure go ahead, sorry for being slow to respond.
