### ISSUE TITLE
New spec failures because of possibly changed method signature/interface

### ISSUE THREAD

**Issue by mhelmetag** [exercism/crystal#97]
In a [recent automatic build](https://travis-ci.org/exercism/crystal/builds/324853419?utm_source=github_status&utm_medium=notification), I saw a spec failure.

Here's the output from travis:
```
running formatting check for: binary
moving files around
running tests for: binary
Error in line 1: while requiring "./spec/binary_spec.cr"
in spec/binary_spec.cr:42: wrong number of arguments for macro 'expect_raises' (given 0, expected 1, 2, 3, 4)
    expect_raises do
    ^~~~~~~~~~~~~
make[2]: *** [test-exercise] Error 1
make[1]: *** [test-exercises] Error 1
make: *** [test] Error 2
The command "make test" exited with 2.
Done. Your build exited with 1.
```

Seems like we might need to do some fiddling here:
https://github.com/exercism/crystal/blob/3ae242da0e9884518a244387790b8d7270753d61/generator/src/generators/binary.cr#L32

**Comment by bmulvihill** [comment]
Ahh yeah I think this was changed in Crystal 0.24.1, I think a specific error needs to be provided
`expect_raises(ArgumentError) do`
